# Generated by Django 2.1.8 on 2019-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_auto_20190530_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
